/**
 * Conventional Commit Formatter Engine
 */

const COMMIT_TYPES = {
  feat: "A new feature",
  fix: "A bug fix",
  docs: "Documentation changes",
  style: "Code formatting / style adjustments",
  refactor: "Code refactoring without feature/bug change",
  test: "Adding or updating unit tests",
  chore: "Build tools or repository maintenance"
};

const COMMIT_EMOJIS = {
  feat: "✨",
  fix: "🐛",
  docs: "📚",
  style: "🎨",
  refactor: "♻️",
  test: "🧪",
  chore: "⚙️"
};

function formatCommitMessage({ type, scope, description, isBreaking = false, withEmoji = false }) {
  if (!COMMIT_TYPES[type]) {
    throw new Error(`Invalid commit type: ${type}. Must be one of: ${Object.keys(COMMIT_TYPES).join(', ')}`);
  }
  if (!description || !description.trim()) {
    throw new Error("Commit description cannot be empty");
  }

  const emojiStr = withEmoji && COMMIT_EMOJIS[type] ? `${COMMIT_EMOJIS[type]} ` : '';
  const scopeStr = scope && scope.trim() ? `(${scope.trim()})` : '';
  const breakingStr = isBreaking ? '!' : '';
  
  return `${emojiStr}${type}${scopeStr}${breakingStr}: ${description.trim()}`;
}

function generateGitHookScript() {
  return `#!/bin/sh
# Conventional Commit validation hook generated by git-commit-craft-cli
commit_msg=$(cat "$1")
pattern="^([a-z]+)(\\([^)]+\\))?!?: .+$"
if ! echo "$commit_msg" | grep -iqE "$pattern"; then
  echo "❌ Error: Commit message must follow Conventional Commits format (e.g., 'feat: add login')"
  exit 1
fi
`;
}

function generateGitHookScript() {
  return `#!/bin/sh
# Conventional Commit validation hook generated by git-commit-craft-cli
commit_msg=$(cat "$1")
pattern="^([a-z]+)(\\([^)]+\\))?!?: .+$"
if ! echo "$commit_msg" | grep -iqE "$pattern"; then
  echo "❌ Error: Commit message must follow Conventional Commits format (e.g., 'feat: add login')"
  exit 1
fi
`;
}

function parseCommitMessage(commitStr) {
  const regex = /^(?:[^\w\s]+\s+)?([a-z]+)(?:\(([^)]+)\))?(!+)?: (.+)$/;
  const match = commitStr.match(regex);
  if (!match) return null;

  return {
    type: match[1],
    scope: match[2] || null,
    isBreaking: !!match[3],
    description: match[4]
  };
}

module.exports = { COMMIT_TYPES, COMMIT_EMOJIS, formatCommitMessage, parseCommitMessage, generateGitHookScript };
module.exports = { COMMIT_TYPES, formatCommitMessage, parseCommitMessage, generateGitHookScript };
